apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-gpu-exporter
  namespace: arena-system
spec:
  selector:
    matchLabels:
      app: node-gpu-exporter
  template:
    metadata:
      labels:
        app: node-gpu-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: accelerator/nvidia_gpu
                operator: Exists
      hostPID: true
      volumes:
      - hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
        name: containerd-sock
      containers:
      - name: node-gpu-exporter
        image: registry.cn-hangzhou.aliyuncs.com/acs/gpu-prometheus-exporter:v1.0.1-b2c2f9b
        imagePullPolicy: Always
        ports:
        - containerPort: 9445
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m
        volumeMounts:
        - mountPath: /run/containerd/containerd.sock
          name: containerd-sock

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: node-gpu-exporter
  namespace: arena-system
  labels:
    app: node-gpu-exporter
    k8s-app: node-gpu-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9445
    protocol: TCP
  selector:
    app: node-gpu-exporter